name: 'Multiplatform Codex Bundle Release'

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-conda:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
          - arch: x86_64
            micromamba-platform: linux-64
          - arch: x86_64
            micromamba-platform: win-64
            CONDA_OVERRIDE_WIN: "10"
          - arch: x86_64
            micromamba-platform: osx-64
            CONDA_OVERRIDE_OSX: "11.0"
          - arch: x86_64
            micromamba-platform: osx-arm64
            CONDA_OVERRIDE_OSX: "11.0"
      fail-fast: false

    steps:
    - name: Checkout Repository
      run: |
        git clone "https://x-token-auth:${{ secrets.TOKEN }}@bitbucket.org/stalker_by/devops-pass-ai.git"
        cd devops-pass-ai
        git checkout lint_fixes
        rm -rf src/assets/codex/codex-bundle/ src/assets/codex/codex-bundle-*.tar.gz src/assets/codex/codex-bundle-*.zip

    - name: Cache Micromamba
      uses: actions/cache@v3
      with:
        path: ~/.micromamba
        key: ${{ runner.os }}-micromamba-${{ matrix.config.arch }}-${{ hashFiles('devops-pass-ai/src/assets/codex/codex.yml') }}
        restore-keys: |
          ${{ runner.os }}-micromamba-${{ matrix.config.arch }}-

    - name: Build Conda Bundle
      env:
        CONDA_OVERRIDE_WIN: ${{ matrix.config.CONDA_OVERRIDE_WIN }}
        CONDA_OVERRIDE_OSX: ${{ matrix.config.CONDA_OVERRIDE_OSX }}
      run: |
        cd devops-pass-ai/src/assets/codex/
        # Download micromamba
        curl -L https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        if [[ "$CONDA_OVERRIDE_WIN" != "" ]]; then
          sed -i 's|- ansible=9.2.0||g' codex.yml
        fi
        # Create conda env
        ./bin/micromamba env create -c conda-forge -f codex.yml -p ./codex-bundle-${{ matrix.config.micromamba-platform }}/ --platform=${{ matrix.config.micromamba-platform }} --yes
        # Clean up
        ./bin/micromamba clean --all --yes
        # Tar the bundle
        tar -czf codex-bundle-${{ matrix.config.micromamba-platform }}-${{ github.sha }}.tar.gz codex-bundle-${{ matrix.config.micromamba-platform }}/

    - name: Upload Conda Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: conda-artifacts-${{ matrix.config.micromamba-platform }}
        path: |
          devops-pass-ai/src/assets/codex/codex-bundle-${{ matrix.config.micromamba-platform }}-${{ github.sha }}.tar.gz
        retention-days: 1

  release:
    needs: build-conda
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download Conda Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: conda-artifacts-*
        merge-multiple: true

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/conda-artifacts-osx-64/*.tar.gz
          artifacts/conda-artifacts-osx-arm64/*.tar.gz
          artifacts/conda-artifacts-linux-64/*.tar.gz
          artifacts/conda-artifacts-win-64/*.tar.gz
