name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-win:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - run: git clone https://x-token-auth:$TOKEN@bitbucket.org/stalker_by/devops-pass-ai.git
      env: 
        TOKEN: "${{secrets.TOKEN}}"
    - run: find .
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: apt install wine
    - run: npm run build:prod && electron-builder build --publish=never --win
